# fly.toml app configuration file generated for titanic-webapp-kjh on 2023-08-08T15:19:57+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "titanic-webapp-kjh"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3
  processes = ["app"]
